version: "3.5"
services:
  bot:
    container_name: wynntils-bot
    networks:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

networks:
  database:
    name: database
